### ISSUE TITLE
Installing gdg

### ISSUE THREAD

**Issue by mintuguptha** [esnet/gdg#103]
HI,
I was trying to backup my grafana dashboards, I have cloned the gdg git project. then tried to run the command: gdg version
outcome:
> gdg version

Command 'gdg' not found, did you mean:

  command 'gtg' from snap getting-things-gnome (0.6)
  command 'gdl' from deb gnudatalanguage
  command 'gdc' from deb gdc
  command 'ddg' from deb python-duckduckgo2
  command 'gtg' from deb gtg
  command 'geg' from deb geg
  command 'gdb' from deb gdb
  command 'gpg' from deb gpg

See 'snap info <snapname>' for additional versions.

could you please provide the detailed steps to download the gdg

**Comment by safaci2000** [comment]
If you just clone the repo you won't be able to just use it.  You can also just download the release from [here](https://github.com/esnet/gdg/releases).  The installation instructions are detailed on [here](https://software.es.net/gdg/docs/installation/)
