### ISSUE TITLE
Wild card option for Dashboards

### ISSUE THREAD

**Issue by mintuguptha** [esnet/gdg#105]
Hello gdg..
I could able to import and export the dashboards, it really helpful.
But my concern is while creating a new context for importing, it asks "List the folders you wish to manage (example: folder1,folder2)? (Blank for General)?".Here manually i was entering the folder names (somewhat hectic). So is there any solution like wildcard which allows to select all the dashboard folders.

expectation:
could able to select all the dashboards rather giving multiple folder names

**Comment by safaci2000** [comment]
That's not currently supported, if you omit the folders, it'll default to only look at General.  This tool was originally designed for an internal use case where we specifically wanted to track a set of folders and maintain them in a VCS system like git while letting other folders be a wild west playground for users.  

We could support a wildcard, as long as we have ensure we don't break existing behavior, I'm open to that.  I think maybe a CLI parameter where it overrides the configuration would be ideal.

**Comment by mintuguptha** [comment]
okay, Thanks for your response @safaci2000
