### ISSUE TITLE
Pull image does not work without authorization in github

### ISSUE THREAD

**Issue by powernic** [esnet/gdg#122]
When I run `docker pull ghcr.io/esnet/gdg:0.3.1 `
I get
`Error response from daemon: Head "https://ghcr.io/v2/esnet/gdg/manifests/0.3.1": denied: denied`

When I use the command in Dockerfile: 
`COPY --from=ghcr.io/esnet/gdg:0.3.1 /opt/gdg/bin/gdg /usr/local/bin/gdg`
 I get 
`failed to solve: ghcr.io/esnet/gdg:0.3.1: failed to authorize: failed to fetch oauth token: unexpected status: 403 Forbidden`

I expected that the image will be pull without authorization in github

**Comment by csg33k** [comment]
I'm assuming since you closed this, that you resolved the issue?

**Comment by powernic** [comment]
@csg33k All right. I had to run the command  `docker logout ghcr.io`
