### ISSUE TITLE
[BUG] Unable to get Admin Auth.  Credentials are missing

### ISSUE THREAD

**Issue by mateuszdrab** [esnet/gdg#143]
**Describe the bug**
After the upgrade from 0.3.1 to 0.4, I get the following error when try to import dashboards:
`FATA[0000] Unable to get Admin Auth.  Credentials are missing `

**To Reproduce**
`/app/gdg -c /app/conf/importer.yml dash import`

I have a cronjob in Kubernetes which worked until release of 0.4 so no changes to the config, reverting to 0.3.1 resolves the issue

Using an API key (service account with Editor rights)

**Expected behavior**
Dashboards sync as always

**Desktop (please complete the following information):**
 - GDG Version: 0.4
 - Grafana Version: [e.g. 8.3.6] 9.4.7
 - Configuration for Importer (token and url redacted)

```
context_name: grafana
contexts:
  grafana:
    adminenabled: false
    ignore_filters: false
    organization: ""
    output_path: /app/exports
    password: ""
    storage: ""
    token: xyz
    url: https://xyz
    user_name: ""
    watched:
      - General
      - Logging
      - General Alerting
  grafana-cloud:
    adminenabled: false
    ignore_filters: false
    organization: ""
    output_path: /app/exports
    password: ""
    storage: ""
    token: xyz
    url: https://xyz
    user_name: ""
    watched:
      - General
      - Logging
      - General Alerting
global:
  debug: true
  ignore_ssl_errors: false
json_logs: false
loglevel: debug
storage_engine:
  any_label:
    access_key_id: ""
    bucket_name: ""
    cloud_type: s3
    kind: cloud
    secret_key: ""
```

**Additional context**
Not sure, unless I'm doing something terribly wrong but I didn't see any breaking changes for this

**Comment by safaci2000** [comment]
That's a legit bug.  Thanks for catching that.

**Comment by safaci2000** [comment]
@mateuszdrab release 0.4.1 as bug fix patch shortly.

**Comment by mateuszdrab** [comment]
> @mateuszdrab release 0.4.1 as bug fix patch shortly.

Thanks @safaci2000 

Glad I was able to help
