### ISSUE TITLE
[BUG] Datasource in dashboard variable has discrepancy in the import vs UI JSON 

### ISSUE THREAD

**Issue by NKR-github** [esnet/gdg#148]
**Describe the bug**
[BUG] Datasource in dashboard variable has discrepancy in the import vs UI JSON 

Because of this it doesn’t recognise the variables as it’s missing the data source.

**To Reproduce**
1. Go to 'Grafana UI download the dashboard containing variables and inside variables > Query Options > Data Source pointing to Prometheus ‘
2. Download the same dashboard via GDG import
3. Compare you will notice 
“datasource”: {
    “type”: “datasource”,
    “uid”: “grafana”  
  },
In UI
VS
 “datasource”: “— Grafana —“, in the grafana import JSON

**Expected behavior**
I expect to see both dashboard json jn UI vs import  to be same.

**Desktop (please complete the following information):**
 - GDG Version:0.4.1 
 - Grafana Version: 9.4.7 (I use provisioning)
- Redhat Linux 8.7

**Comment by safaci2000** [comment]
I'm not able to re-create this bug. 

1. Created a dashboard with some variables as you described though that seems unrelated to your issue. 
2. The datasource and UID both match in the JSON from the UI and the export.  Here's an example that I used.

```json
UI:
        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },

GDG:

        "datasource": {
          "type": "datasource",
          "uid": "grafana"
        },
 ```

**Comment by NKR-github** [comment]
> I'm not able to re-create this bug.
> 
> 1. Created a dashboard with some variables as you described though that seems unrelated to your issue.
> 2. The datasource and UID both match in the JSON from the UI and the export.  Here's an example that I used.
> 
> ```json
> UI:
>         "datasource": {
>           "type": "datasource",
>           "uid": "grafana"
>         },
> 
> GDG:
> 
>         "datasource": {
>           "type": "datasource",
>           "uid": "grafana"
>         },
> ```

Thanks for looking into this.
I have resolved the issue. The issue was noticed only one few existing dashboards (esp the ones straight from grafana labs example windows Prometheus dashboard ) after I upgraded grafana from 8 to 9 and after that enabling provisioning.

I resolved it by adding this block before every variable definition in those problematic dashboards. After that the gdg imports were working fine for those dashboards.

         "datasource": {
             "type": "datasource",
             "uid": "grafana"
         },
