### ISSUE TITLE
[BUG] invalid cross-device link for  [dashboard]

### ISSUE THREAD

**Issue by madhur** [esnet/gdg#194]
**Describe the bug**
While downloading the dashboards from our grafana, I get this error

```
 gdg backup dashboards download                                                                                               [☸ eks-pt-v2 (mec)]
ERRO[0000] blob (key "agamotto.json") (code=Unknown): rename /tmp/agamotto.json.17851cdab3625e2d.tmp /home/madhur/github/personal/grafana_backup/output/org_1/dashboards/My11c/agamotto.json: invalid cross-device link for agamotto 
ERRO[0000] blob (key "agamotto-graphite.json") (code=Unknown): rename /tmp/agamotto-graphite.json.17851cdab7737698.tmp /home/madhur/github/personal/grafana_backup/output/org_1/dashboards/My11c/agamotto-graphite.json: invalid cross-device link for agamotto-graphite 
ERRO[0000] blob (key "agamotto_copy.json") (code=Unknown): rename /tmp/agamotto_copy.json.17851cdabb89baba.tmp /home/madhur/github/personal/grafana_backup/output/org_1/dashboards/My11c/agamotto_copy.json: invalid cross-device link for agamotto_copy 
```

**To Reproduce**
1. I am on folder "/home/github/personal/grafana_backup"
2. Create The file with following contents

```
context_name: main
contexts:
    local:
        output_path: local
        url: http://localhost:4000
        token:
    main:
        ignore_filters: false
        output_path: output
        url: https://<my grafana url>
        token: 
        watched:
            - Folder
global:
    debug: true
    ignore_ssl_errors: false
json_logs: false
loglevel: debug
```
3. Run the command  `gdg backup dashboards download `
4. I get this error.

It is worth mentioning that `/home/github` is symlinked to folder on another disk. May be that could be the cause. However, its still a bug.

Update: I tried running this on folder `/home/grafana_backup` and still get the same error.

**Expected behavior**
The backup should succeed. This was earlier working on previous version.

**Desktop (please complete the following information):**
 - GDG Version: 
 - Grafana Version: 7.1.1
 - Configuration for Importer 0.5.0

**Additional context**

**Comment by safaci2000** [comment]
This feels like a symlink behavior issue.  I need to play around a little bit with that behavior.  Symlinks are not treated the same as folders/files in go.  

Just to confirm.

/home/github/personal/grafana_backup is your $CWD, you're expecting data to be written to:  /home/github/personal/grafana_backup.

The backed up data is valid folders, no sym links there.  Also you re-structured anything that needed to address the breaking changes mentioned in the release.  ie.  if you're importing anything it would be under /org_1/ etc rather than at the base of the backup folder?

With /home/github being a symlink to a different location?  

Does that all sound about right?



I'll try to re-create this locally.  One clarification, you're using a token based auth?

**Comment by madhur** [comment]
> /home/github/personal/grafana_backup is your working directory where you're invoking GDG from, assuming you have > a config/import.yml in that path as well. You're expecting data to be written to: /home/github/personal/grafana_backup.

That is right

> The backed up data is valid folders, no sym links there. Also you re-structured anything that needed to address the       
> breaking changes mentioned in the release. ie. if you're importing anything it would be under /org_1/ etc rather than   
> at the base of the backup folder?

I saw it automatically created the new folder structure though no files were present in it due to failures.  The output from previous version was there in `output` folder which was untouched.

I never import. Always export to take the backup and hence cannot comment on the import part.

> With /home/github being a symlink to a different location?

Yes, below shows the symlink. 
```
lrwxrwxrwx    - madhur 11 May 23:08  github -> /run/media/madhur/centos/home/madhur/github
```
However, as I mentioned, I tried from the non-symlinked folder but got the same errors.

Yes, using token based auth.

Note: After downgrading to 0.4.5, backup worked fine.

**Comment by safaci2000** [comment]
Okay thank you for all the info and confirming that 0.4.5 worked, that's helpful.
