### ISSUE TITLE
[HELP] Local filesystem storage

### ISSUE THREAD

**Issue by bahmanm** [esnet/gdg#198]
First off, thanks for the cool software!

I looked through the docs but I couldn't find any information on simply using the local machine's filesystem for storage (at least for testing purposes.)  

Is it possible?  Did I miss anything obvious?

**Comment by csg33k** [comment]
Yup, there's also a little wizard that should let you create a new config  `gdg context new <label>` it doesn't support all options but it does work for your basic standard use case. (ie local pull)
