### ISSUE TITLE
[BUG] renaming causes invalid cross-device link

### ISSUE THREAD

**Issue by darkobas** [esnet/gdg#205]
**Describe the bug**
you can not rename to different filesystems

ERRO[0000] blob (key "alerts.json") (code=Unknown): rename /tmp/alerts.json.178cb5364cac39b7.tmp /home/test/grafana/test-graf/org_1/folders/alerts.json: invalid cross-device link for alerts

**Desktop (please complete the following information):**
 - GDG Version: 0.5.0
 - Grafana Version: 9+

**Comment by madhur** [comment]
This issue has been fixed in master branch https://github.com/esnet/gdg/pull/195

**Comment by darkobas** [comment]
thanx for info and fast response.
