### ISSUE TITLE
[BUG] Datasources deletion fails with 400 when using token auth

### ISSUE THREAD

**Issue by maxout123** [esnet/gdg#206]
**Describe the bug**

Datasources deletion fails with 400 when using token auth

```
logger=authn.service t=2023-10-24T08:53:39.621212351Z level=warn msg="Failed to authenticate request" client=auth.client.basic error="[password-auth.empty] no password provided"
logger=context userId=0 orgId=0 uname= t=2023-10-24T08:53:39.621282794Z level=info msg= error="[password-auth.empty] no password provided" remote_addr=100.127.180.0 traceID=
logger=context userId=0 orgId=0 uname= t=2023-10-24T08:53:39.621362797Z level=info msg="Request Completed" method=DELETE path=/api/datasources/2 status=400 remote_addr=100.127.180.0 time_ms=0 duration=780.602µs size=120 referer= handler=/api/datasources/:id
```

**To Reproduce**
Create token auth context
./gdg backup connections download
./gdg backup connections upload

```
ERRO[0002] error on deleting datasource test connection with response status code does not match any response statuses defined for this endpoint in the swagger spec (status 400): {}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15f84b1]
```

**Expected behavior**
Datasources deleted and uploaded normally

**Desktop (please complete the following information):**
 - GDG Version: 0.5.0
 - Grafana Version: [e.g. 10.1.5] 

**Additional context**
Another question why gdg still tries to connect with basic auth despite context is configured with token:
```
logger=authn.service t=2023-10-24T08:53:39.109379157Z level=warn msg="Failed to authenticate request" client=auth.client.basic error="[password-auth.empty] no password provided"
logger=context userId=0 orgId=0 uname= t=2023-10-24T08:53:39.109473043Z level=info msg= error="[password-auth.empty] no password provided" remote_addr=100.127.210.128 traceID=
```

**Comment by safaci2000** [comment]
Can you provide with the configuration you used (without secrets). 

There's some bootstrapping that GDG does to set the correct Org if supported.  Some of this has been a bit more polished in master, but it's likely related to that.  There are also endpoints that are only supported with basic auth.  

https://software.es.net/gdg/docs/tutorials/orgs_auth/.

**Comment by maxout123** [comment]
```
context_name: grafana2
storage_engine: {}
contexts:
    grafana2:
        storage: ""
        enterprise_support: false
        url: https://grafana2.url.tld
        token: "<here is org admin token>"
        user_name: ""
        password: ""
        organization_id: 1
        watched:
            - General
        connections: {}
        datasources: {}
        filter_override: null
        output_path: /tmp/exports/grafana2
global:
    debug: true
    ignore_ssl_errors: true

```

(I have also tried to remove user_name, password and organization_id lines, still no luck)

```
./gdg backup connections download
./gdg backup connections upload

```

Also, there are some connections with empty basic auth on every gdg operation with this config. I believe gdg should not try to use basic auth at all if it is not configured in config.
