### ISSUE TITLE
[BUG] Alert Rules List not showing up after restore in Grafana 7

### ISSUE THREAD

**Issue by laertis** [esnet/gdg#247]
# SETUP

- gdg version: `0.5.1`
- grafana version: `7.2.0`/`7.5.17`

To backup `Grafana v7.2.0` I run
```
gdg backup alertnotifications download
gdg backup connections download
gdg backup dashboards download
gdg backup folders download
gdg backup organizations download
gdg backup teams download
gdg backup users download
```

To restore in `Grafana v7.5.17` I run
```
gdg backup organizations upload
gdg backup folders upload
gdg backup teams upload
gdg backup users upload
gdg backup connections upload
gdg backup alertnotifications upload
gdg backup dashboards upload
```

# PROBLEM
In `Grafana v7.5.17` where I restored from the `Grafana v7.2.0` backup, although I'm able to see the alerts configured in individual panels in the `Alert` tab when I edit the panel, I cannot see any alert rule under`http://<grafana_url>/alerting/list`

Moreover, the "heart" icon is missing from the panels that has the configured alert

# UPDATE 1

I reproduced the same issue after restoring to the same Grafana version as the Grafana I took the backup from `7.2.0` -> `7.2.0`

# UPDATE 2

While trying different things I noticed that upon **saving** (_without changing anything_) the restored dashboard through the Grafana UI, brings back the alert heart icons on the panels they were configured against, as well as the the alert rules in the alert rule list

Investigating further led me to discover that Grafana actually has a [different JSON schema](https://community.grafana.com/t/creating-dashboards-with-the-api-from-an-exported-one-from-the-web-app/19665) when exporting/importing through the UI interface and another one through the API

My assumption is that gdg uses chromium with `dashboards/import` API instead of the Grafana dashboard API `api/dashboards/db` which causes the issue

## Workaround Fix

In order to fix the alert issue, after restoring all configuration through gdg, I re-downloaded all dashboards through the [Grafana HTTP API](https://grafana.com/docs/grafana/v7.2/http_api/dashboard/) this time and re-uploaded them through the same API endpoint after merging the json with the following `{overwrite: true, dashboard: {id: null}}` based on this gist
- https://gist.github.com/crisidev/bd52bdcc7f029be2f295

This creates a new saved version of the dashboard and manages to solve the issue. The heart icon on the panels as well as the alert rules in `http://_grafana_url_/alerting/list` are now visible

Using `jq` in the same way but using the gdg downloaded dashboard instead of the ones downloaded from the Grafana HTTP API does not work because they don't have the same schema and produces the following error
- `[{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}]`

If one performs the jq operation on the gdg downloaded dashboard json and opens the edited json will realize that there is no top-level `dashboard` object and the operation just adds a nested object with the provided key values

**Comment by safaci2000** [comment]
Reference: https://github.com/esnet/gdg/issues/67

and https://github.com/grafana/grafana/pull/43525
