### ISSUE TITLE
[BUG] Configuration Loading issue

### ISSUE THREAD

**Issue by efflamlemaillet** [esnet/gdg#317]
I am testing gdg to backup dashboard and it works great
but i found the following behavior of the option `-c` could be missleading:

**Describe the bug**
Config file without yaml or yml extension passed with `-c` or `--config`  are ignored without warning even if the syntax is correct.
Even more the program overwrite the config at `./config/importer.yml` if it exists.

**To Reproduce**
1. Generate a default config :  `./gdg tools ctx list`
2. Change the current context `sed -i 's/context_name: qa/context_name: testing/' config/importer.yml`
3. Copy the file to another location `cp config/importer.yml conf`
4. The copy is correct but not loaded and it overwrite the config present at default location: 
```
#see the default config modified (context is testing)
/app # ./gdg  tools ctx list
┌────────────┬────────┐
│ CONTEXT    │ ACTIVE │
├────────────┼────────┤
│ production │ false  │
│ qa         │ false  │
│ *testing   │ true   │
└────────────┴────────┘
#try to use the copy without extension 
/app # ./gdg -c conf  tools ctx list
2024-11-08 15:29:59 INF No configuration file has been found, creating a default configuration
┌────────────┬────────┐
│ CONTEXT    │ ACTIVE │
├────────────┼────────┤
│ production │ false  │
│ *qa        │ true   │
│ testing    │ false  │
└────────────┴────────┘
# The default config has been overwritten (context is back to qa)
/app # ./gdg  tools ctx list
┌────────────┬────────┐
│ CONTEXT    │ ACTIVE │
├────────────┼────────┤
│ production │ false  │
│ *qa        │ true   │
│ testing    │ false  │
└────────────┴────────┘
```

**Expected behavior**
1. A valid file passed by cli argument should be used regardless of it extension
Or at least if this behavior is not desired a WARN about an invalid argument should be printed.
And in my opinion the program should stop if the user expected configuration is not used.

2. The presence of default file must be checked before creating a default configuration over it

**Desktop (please complete the following information):**
 - GDG Version: docker image ghcr.io/esnet/gdg:0.7.1

**Comment by efflamlemaillet** [comment]
I did not know about the other syntax, i understand.
In my case i use gitlab-ci variables files so the file name has no extension initially.
Anyway it is more about logging and documentation about 1. if there are many extension supported.

the fact that is overwrite the config/importer.yml in case of an bad file passed to `-c` is still a issue i think.

I agree that keeping a tool that generate a example of config is a nice feature for beginners and it also helps to migrate when syntax changes.

**Comment by safaci2000** [comment]
I added a fix so that it's able to handle missing extension you ran into but it will also require a valid configuration for crud and tooling operation. It doesn't really make sense to have a default on some non existent Grafana server. 

I'll polish this up and add documentation before releasing the next version.
