### ISSUE TITLE
Support importing Grafana panels

### ISSUE THREAD

**Issue by efekete** [esnet/gdg#67]
Apparently, Grafana does not plan to support importing library panels through POST API and they want people to use import dashboard API that is not documented.

https://github.com/grafana/grafana/issues/44003
https://github.com/grafana/grafana/pull/43525

It would be great if you could use that import API to support that feature.

I was planning on writing PR, but currently have busy schedule.

**Comment by safaci2000** [comment]
Just to re-iterate what is mentioned in those two posts.  

Currently GDG uses the [REST Api](https://grafana.com/docs/grafana/latest/http_api/dashboard/) for dashboards, specifically  and particularly this endpoint

```sh
POST /api/dashboard/db/
```

instead you'd like to use the:

```sh
POST /api/dashboards/import
```

Which in theory would support library imports? Is that the ask?

**Comment by efekete** [comment]
Yes, although it sound irrational when you say it like that :D

If you ask me that should be fixed from Grafana side as they are not giving any documented way to do that, but as it seems for some reason they are not willing to support that at this point.

I checked the code and that API endpoint:
https://github.com/grafana/grafana/blob/acb791bdd69b46a8ada3ec7cf5bb5a31003b005c/pkg/api/api.go#L342
uses same function as frontend uses:
https://github.com/grafana/grafana/blob/641e34e341c2a5c8481a8bad2317ed4e75e1c846/pkg/api/plugins.go#L220
which has this part where panels are imported:
https://github.com/grafana/grafana/blob/641e34e341c2a5c8481a8bad2317ed4e75e1c846/pkg/api/plugins.go#L252

I already used this tool for exporting and checked that if that function is added to current API call, it all works as expected.

So we can add some argument or configuration option to use this if we want to make sure this doesn't brake backwards compatibility.
If you, too, don't have time, at some point I'll probably add support for that and can create a PR.

**Comment by safaci2000** [comment]
Well, if this is the new way of importing dashboards, that's fine but it would be nice if at least grafana updated the documentation accordingly. 

gdg uses an API library for grafana called grafana-sdk. So in order to do this we'd either have to commit back upstream or develop al alternative pattern to make calls. 

I'm not against this change just want to make sure it is the "proper" solution before we go down that rabbit hole.

**Comment by efekete** [comment]
Sounds good, I agree it should be done properly.

 I can check the library and open the feature request accordingly if needed. I can also open an issue on Grafana side asking for documentation.

**Comment by safaci2000** [comment]
I poked their slack asking for more info.  I'll open a ticket asking for documentation on Monday.

**Comment by safaci2000** [comment]
https://github.com/grafana/grafana/issues/44383 Opened a ticket for Grafana.

**Comment by efekete** [comment]
Great! Let me know if I can help with anything.

**Comment by safaci2000** [comment]
@efekete Grafana responded to the ticket, do you mind giving a bit more context? You would know best what is/ isn't working.

**Comment by vincent-gou** [comment]
Hi, I'd really interested if it could be implemented in gdg. 
Library panel import would be a great feature ! :-)
Thanks for work done.

**Comment by csg33k** [comment]
It's become really needed for us (ESNet) internally as well so this should be coming soon with the next release.

**Comment by safaci2000** [comment]
This should be fixed in 0.4.0. Next release

**Comment by safaci2000** [comment]
merged to mainline.
