### ISSUE TITLE
CRUD for Teams and Team Memberships

### ISSUE THREAD

**Issue by FrankAnk** [esnet/gdg#96]
It would be great if we had this to manage Teams as well as Users
see: https://grafana.com/docs/grafana/latest/http_api/team/

**Comment by safaci2000** [comment]
hello @FrankAnk.  I'll have a look to see if the SDK supports this.  Do you know by any chance when it was released, I don't think team is a concept I was familiar with till now.

**Comment by FrankAnk** [comment]
Teams has been part of Grafana for a while, you can authorize Teams to access folders. The users are added to the team as members to receive the rights assigned to the team. 
This concept was introduced with Version 5.1 and we are now at Version 8.5.

See: https://grafana.com/blog/2022/03/14/how-to-best-organize-your-teams-and-resources-in-grafana/
and: https://grafana.com/tutorials/create-users-and-teams/

HTTP API Reference: https://grafana.com/docs/grafana/latest/http_api/

**Comment by safaci2000** [comment]
This requires SDK Changes so will revisit this a bit later.  There's some talk about an official (community supported) SDK so maybe that'll be more feature complete, otherwise will try to address this time pending.  Per usual any PR is welcome

**Comment by csg33k** [comment]
@FrankAnk I'm revisiting this ticket again. Just to clarify you're looking to save the state of the team memberships in grafana, not to add/delete users via GDG, correct?

**Comment by FrankAnk** [comment]
> @FrankAnk I'm revisiting this ticket again. Just to clarify you're looking to save the state of the team memberships in grafana, not to add/delete users via GDG, correct?

This is correct!
We have the users authenticated using LDAP, but team memberships need to be defined in Grafana and managed with GDG. As of Grafana version 9.3 we would also like to manage notification channels and alert rules with GDG if possible.

**Comment by mc-chaos** [comment]
Hi @FrankAnk ,
de are using this script to sync users to Team members.
[LDAP sync](https://github.com/NovatecConsulting/grafana-ldap-sync-script)
Regards, Sascha

**Comment by FrankAnk** [comment]
Thanks @mc-chaos Sascha, i'll give it a try!
I was hoping to just use one tool to manage everything.

Regards, Franklin
